package protos

import (
	"demo/app/common/consts"

	"github.com/ma-guo/niuhe"
)

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改, 不需要生成本文件时请在 langs 中移除 route 配置

// api 模块下的所有路由数组
var RouteItems = []*niuhe.RouteItem{
	{Method: "GET", Path: "/api/config/page/", Name: "分页查询获取Config信息"},
	{Method: "GET", Path: "/api/config/form/", Name: "查询获取Config信息"},
	{Method: "POST", Path: "/api/config/add/", Name: "添加Config信息"},
	{Method: "POST", Path: "/api/config/update/", Name: "更新Config信息"},
	{Method: "DELETE", Path: "/api/config/delete/", Name: "删除Config信息"},
	{Method: "GET", Path: "/api/hellow/world/", Name: "示例接口"},
	{Method: "GET", Path: "/api/hellow/docs/", Name: "协议文档"},
	{Method: "GET", Path: "/api/hellow/web/", Name: "网页示例"},
	{Method: "GET", Path: "/api/xxx/yyy/", Name: "RPC测试用例", Codes: []niuhe.IntConstItem{
		consts.LanguageType.ZH_CN, // 1 - 简体中文
		consts.Errors.NOT_FOUND,   // 404 - 查找的数据不存在,
	}},
}
