package protos

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

// 系统配置表
type ConfigItem struct {
	Id       int64  `json:"id" zpf_name:"id"`                       //	id
	Name     string `json:"name" zpf_name:"name" zpf_reqd:"true"`   //	配置名称
	Value    int64  `json:"value" zpf_name:"value" zpf_reqd:"true"` //	配置值
	CreateAt string `json:"create_at" zpf_name:"create_at"`         //	创建时间
	UpdateAt string `json:"update_at" zpf_name:"update_at"`         //	更新时间
}

// 请求 Config 信息
type ConfigFormReq struct {
	Id int64 `json:"id" zpf_name:"id" zpf_reqd:"true"`
}

// 分页查询 Config 信息
type ConfigPageReq struct {
	Page  int   `json:"page" zpf_name:"page" zpf_reqd:"true"`   //	页码
	Size  int   `json:"size" zpf_name:"size" zpf_reqd:"true"`   //	每页数量
	Value int64 `json:"value" zpf_name:"value" zpf_reqd:"true"` //	配置值
}

// 分页查询 Config 信息
type ConfigPageRsp struct {
	Total int64         `json:"total" zpf_name:"total" zpf_reqd:"true"` //	总数
	Items []*ConfigItem `json:"items" zpf_name:"items"`                 //	Config信息
}

// 批量删除 Config 信息
type ConfigDeleteReq struct {
	Ids []int64 `json:"ids" zpf_name:"ids"` //	记录id列表
}

// Config 无数据返回
type ConfigNoneRsp struct {
}

// 测试请求
type HelloReq struct {
	Name string `json:"name" zpf_name:"name" zpf_reqd:"true"` //	用户名
}

// 测试响应
type HelloRsp struct {
	Greeting string `json:"greeting" zpf_name:"greeting" zpf_reqd:"true"` //	问候语
}

// RPC测试用例请求参数
type XxxYyyReqMsg struct {
	CountryCode int    `json:"country_code" zpf_name:"country_code"`                 //	国家码
	PhoneNumber string `json:"phone_number" zpf_name:"phone_number" zpf_reqd:"true"` //	用户名
	Password    string `json:"password" zpf_name:"password" zpf_reqd:"true"`         //	密码
	Appid       string `json:"appid" zpf_name:"appid" zpf_reqd:"true"`               //	应用ID
}

// RPC测试用例返回参数
type XxxYyyRspMsg struct {
	OpenId      string `json:"open_id" zpf_name:"open_id" zpf_reqd:"true"`           //	用户open_id
	AccountInfo string `json:"account_info" zpf_name:"account_info" zpf_reqd:"true"` //	账户信息
}
