package protos

import (
	"demo/app/common/consts"
	"github.com/ma-guo/niuhe"
)

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改, 不需要生成本文件时请在 langs 中移除 route 配置

// niuhe 生成的路由结构
type RouteItem struct {
	Method string               `json:"method"` // API 请求方法
	Path   string               `json:"path"`   // API 请求路径
	Name   string               `json:"name"`   // API 名称
	Codes  []niuhe.IntConstItem `json:"codes"`  // API 限定错误码
}

// api 模块下的所有路由数组
var RouteItems = []*RouteItem{
	{Method: "GET", Path: "/api/config/page/", Name: "分页查询获取 Config 信息"},
	{Method: "GET", Path: "/api/config/form/", Name: "查询获取 Config 信息"},
	{Method: "POST", Path: "/api/config/add/", Name: "添加 Config 信息"},
	{Method: "POST", Path: "/api/config/update/", Name: "更新 Config 信息"},
	{Method: "DELETE", Path: "/api/config/delete/", Name: "删除 Config 信息"},
	{Method: "GET", Path: "/api/hellow/world/", Name: "示例接口"},
	{Method: "GET", Path: "/api/hellow/docs/", Name: "协议文档"},
	{Method: "GET", Path: "/api/hellow/web/", Name: "网页示例"},
	{Method: "GET", Path: "/api/xxx/yyy/", Name: "RPC测试用例", Codes: []niuhe.IntConstItem{
		consts.LanguageType.ZH_CN, // 1 - 简体中文
		consts.Errors.NOT_FOUND,   // 404 - 查找的数据不存在,
	}},
}
