package views

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import (
	"demo/app/api/protos"

	"github.com/ma-guo/niuhe"
)

type _Gen_Xxx struct{}

// RPC测试用例
func (v *_Gen_Xxx) Yyy_GET(c *niuhe.Context, req *protos.XxxYyyReqMsg, rsp *protos.XxxYyyRspMsg) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
