package views

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import (
	"demo/app/api/protos"

	"github.com/ma-guo/niuhe"
)

type _Gen_Config struct{}

// 分页查询获取Config信息
func (v *_Gen_Config) Page_GET(c *niuhe.Context, req *protos.ConfigPageReq, rsp *protos.ConfigPageRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 查询获取Config信息
func (v *_Gen_Config) Form_GET(c *niuhe.Context, req *protos.ConfigFormReq, rsp *protos.ConfigItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 添加Config信息
func (v *_Gen_Config) Add_POST(c *niuhe.Context, req *protos.ConfigItem, rsp *protos.ConfigItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 更新Config信息
func (v *_Gen_Config) Update_POST(c *niuhe.Context, req *protos.ConfigItem, rsp *protos.ConfigItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 删除Config信息
func (v *_Gen_Config) Delete_DELETE(c *niuhe.Context, req *protos.ConfigDeleteReq, rsp *protos.ConfigNoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
