package views

// Generated by niuhe.idl

import (
	"demo/app/api/protos"
	"encoding/json"
	"net/http"
	"os"

	"github.com/flosch/pongo2"

	"github.com/ma-guo/niuhe"
)

type Hellow struct {
	_Gen_Hellow
}

// 示例接口
func (v *Hellow) World_GET(c *niuhe.Context, req *protos.HelloReq, rsp *protos.HelloRsp) error {
	rsp.Greeting = "Hello World " + req.Name
	return nil
}

// 协议文档
func (v *Hellow) Docs_GET(c *niuhe.Context) {
	docs, err := os.ReadFile("./docs/swagger.json")
	if err != nil {
		niuhe.LogError("read docs file failed: %v", err)
		return
	}
	data := make(map[string]any)
	json.Unmarshal(docs, &data)
	c.JSON(http.StatusOK, data)
}

// 网页示例
func (v *Hellow) Web_GET(c *niuhe.Context) {
	// 在此实现具体方法, 需要自行处理请求参数和返回数据
	c.HTML(http.StatusOK, "index.html", pongo2.Context{
		"title":   "网页 title",
		"message": "这是一条消息",
	})
}

// 测试 validator
func (v *Hellow) Validator_GET(c *niuhe.Context, req *protos.HellowValidatorReqMsg, rsp *protos.HellowValidatorRspMsg) error {
	rsp.Text = "通过验证"
	return nil
}

func init() {
	GetModule().Register(&Hellow{})
}
