package views

// Generated by niuhe.idl

import (
	"demo/app/api/protos"
	"encoding/json"
	"net/http"
	"os"

	"github.com/ma-guo/niuhe"
)

type Hello struct {
	_Gen_Hello
}

// 示例接口
func (v *Hello) World_GET(c *niuhe.Context, req *protos.HelloReq, rsp *protos.HelloRsp) error {
	rsp.Greeting = "Hello World " + req.Name
	return nil
}

// 协议文档
func (v *Hello) Docs_GET(c *niuhe.Context) {
	docs, err := os.ReadFile("./docs/swagger.json")
	if err != nil {
		niuhe.LogError("read docs file failed: %v", err)
		return
	}
	data := make(map[string]any)
	json.Unmarshal(docs, &data)
	c.JSON(http.StatusOK, data)
}

func init() {
	GetModule().Register(&Hello{})
}
