package views

// Generated by niuhe.idl
import (
	"demo/app/api/protos"

	coreViews "github.com/ma-guo/admin-core/app/v1/views"
	"github.com/ma-guo/niuhe"
)

var thisModule *niuhe.Module

func GetModule() *niuhe.Module {
	if thisModule == nil {
		// thisModule = niuhe.NewModule("api")
		// api 级权限处理

		coreViews.GetProtocol().AddRoute("", protos.RouteItems)

		coreViews.AddSkipUrl("/api/hellow/docs/")      // 不需要认证的路径都加入到这里来
		coreViews.AddSkipUrl("/api/hellow/validator/") // 不需要认证的路径都加入到这里来
		thisModule = niuhe.NewModuleWithProtocolFactoryFunc("api", func() niuhe.IApiProtocol {
			return coreViews.GetProtocol() // 使用 coreViews 中定义的协议处理
		})
	}
	return thisModule
}
