package views

// Generated by niuhe.idl

import (
	"demo/app/api/protos"

	"github.com/ma-guo/niuhe"
)

type Xxx struct {
	_Gen_Xxx
}

// RPC测试用例
func (v *Xxx) Yyy(c *niuhe.Context, req *protos.XxxYyyReqMsg, rsp *protos.XxxYyyRspMsg) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
func init() {
	GetModule().Register(&Xxx{})
}
