

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

 /** 错误类型 */
 declare enum Errors {
    /** 查找的数据不存在 */
    NOT_FOUND = 404,
 }

 /** 语言枚举类 */
 declare enum Language {
    /** 中文 */
    ZH = "zh",
    /** 英文 */
    EN = "en",
 }

 /** 语言类型枚举 */
 declare enum LanguageType {
    /** 简体中文 */
    ZH_CN = 1,
    /** 繁体中文 */
    ZH_TW = 2,
 }

    