

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

interface Rsp<T> {
    result: number
    data: T
    message: string
}

declare namespace Demo {
    /** 分页查询Config信息 */
    interface ConfigPageReq {
        /** 页码 */
        page: number,
        /** 每页数量 */
        size: number,
        /** 配置名称 */
        name: string,
        /** 配置值 */
        value: number,
    }

    /** 系统配置表 */
    interface ConfigItem {
        /** id */
        id: number,
        /** 配置名称 */
        name: string,
        /** 配置值 */
        value: number,
        /** 创建时间 */
        create_at: string,
        /** 更新时间 */
        update_at: string,
    }

    /** 分页查询Config信息 */
    interface ConfigPageRsp {
        /** 总数 */
        total: number,
        /** Config信息 */
        items: ConfigItem[],
    }

    /** 请求Config信息 */
    interface ConfigFormReq {
        id: number,
    }

    /** 批量删除Config信息 */
    interface ConfigDeleteReq {
        /** 记录id列表 */
        ids: number[],
    }

    /** Config无数据返回 */
    interface ConfigNoneRsp {
    }

    /** 测试请求 */
    interface HelloReq {
        /** 用户名 */
        name: string,
    }

    /** 测试响应 */
    interface HelloRsp {
        /** 问候语 */
        greeting: string,
    }

    /** 空请求 */
    interface NoneReq {
    }

    /** 空响应 */
    interface NoneRsp {
    }

    /** RPC测试用例请求参数 */
    interface XxxYyyReqMsg {
        /** 用户名 */
        name: string,
        /** 密码 */
        password: string,
    }

    /** RPC测试用例返回参数 */
    interface XxxYyyRspMsg {
        /** 用户open_id */
        open_id: string,
        /** 账户信息 */
        account_info: string,
    }

    /** 测试 validator请求参数 */
    interface HellowValidatorReqMsg {
        /** 名字 长度:4-10 */
        name: string,
        /** 年龄 数值范围:10-20 */
        age: number,
        /** 变量 正则表达式:[A-Za-z][a-zA-Z0-9_]* */
        var: string,
    }

    /** 测试 validator返回参数 */
    interface HellowValidatorRspMsg {
        /** 消息 */
        text: string,
    }

}
