
// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import { ajax_get, ajax_post, ajax_any } from "./request";

 /**
  * 分页查询获取Config信息 
  * @path get /api/config/page/
  * @return Demo.ConfigPageRsp
*/
 export const getApiConfigPage = (data: Demo.ConfigPageReq): Promise<Rsp<Demo.ConfigPageRsp>> => {
    return ajax_any("get", "/api/config/page/", data);
 }

 /**
  * 查询获取Config信息 
  * @path get /api/config/form/
  * @return Demo.ConfigItem
*/
 export const getApiConfigForm = (data: Demo.ConfigFormReq): Promise<Rsp<Demo.ConfigItem>> => {
    return ajax_any("get", "/api/config/form/", data);
 }

 /**
  * 添加Config信息 
  * @path post /api/config/add/
  * @return Demo.ConfigItem
*/
 export const postApiConfigAdd = (data: Demo.ConfigItem): Promise<Rsp<Demo.ConfigItem>> => {
    return ajax_any("post", "/api/config/add/", data);
 }

 /**
  * 更新Config信息 
  * @path post /api/config/update/
  * @return Demo.ConfigItem
*/
 export const postApiConfigUpdate = (data: Demo.ConfigItem): Promise<Rsp<Demo.ConfigItem>> => {
    return ajax_any("post", "/api/config/update/", data);
 }

 /**
  * 删除Config信息 
  * @path delete /api/config/delete/
  * @return Demo.ConfigNoneRsp
*/
 export const deleteApiConfigDelete = (data: Demo.ConfigDeleteReq): Promise<Rsp<Demo.ConfigNoneRsp>> => {
    return ajax_any("delete", "/api/config/delete/", data);
 }

 /**
  * 示例接口 
  * @path get /api/hellow/world/
  * @return Demo.HelloRsp
*/
 export const getApiHellowWorld = (data: Demo.HelloReq): Promise<Rsp<Demo.HelloRsp>> => {
    return ajax_any("get", "/api/hellow/world/", data);
 }

 /**
  * 协议文档 
  * @path get /api/hellow/docs/
  * @return Demo.NoneRsp
*/
 export const getApiHellowDocs = (data: Demo.NoneReq): Promise<Rsp<Demo.NoneRsp>> => {
    return ajax_any("get", "/api/hellow/docs/", data);
 }


 /**
  * RPC测试用例 
  * @path get /api/xxx/yyy/
  * @return Demo.XxxYyyRspMsg
  * @codes 错误码如下
  * - ZH_CN(1) 简体中文
  * - NOT_FOUND(404) 查找的数据不存在
*/
 export const getApiXxxYyy = (data: Demo.XxxYyyReqMsg): Promise<Rsp<Demo.XxxYyyRspMsg>> => {
    return ajax_any("get", "/api/xxx/yyy/", data);
 }

 /**
  * 测试 validator 
  * @path get /api/hellow/validator/
  * @return Demo.HellowValidatorRspMsg
*/
 export const getApiHellowValidator = (data: Demo.HellowValidatorReqMsg): Promise<Rsp<Demo.HellowValidatorRspMsg>> => {
    return ajax_any("get", "/api/hellow/validator/", data);
 }

