
// Generated by niuhe.idl, search "niuhe" plugin for vscode
// 重新生成时本文件将被复写, 请不要手动修改. 配置 "tstypes" 可指定新路径

declare namespace Demo {

	// gen enum const

	/**
	* 语言枚举类 
	*
	* 成员包括 ZH("zh"), EN("en")
	*/
	enum Language {
		/** 中文 */
		ZH = "zh",
		/** 英文 */
		EN = "en",
	}

	/**
	* 语言类型枚举 
	*
	* 成员包括 ZH_CN(1), ZH_TW(2)
	*/
	enum LanguageType {
		/** 简体中文 */
		ZH_CN = 1,
		/** 繁体中文 */
		ZH_TW = 2,
	}

	// gen model api


	/**
	 * 系统配置表
	 *
	 * 成员包括 id, name, value, create_at, update_at
	 */
	interface ConfigItem {
		/** id */
		id: number;
		/** 配置名称 */
		name: string;
		/** 配置值 */
		value: number;
		/** 创建时间 */
		create_at: string;
		/** 更新时间 */
		update_at: string;
	}

	/**
	 * 请求 Config 信息
	 *
	 * 成员包括 id
	 */
	interface ConfigFormReq {
		id: number;
	}

	/**
	 * 分页查询 Config 信息
	 *
	 * 成员包括 page, size, value
	 */
	interface ConfigPageReq {
		/** 页码 */
		page: number;
		/** 每页数量 */
		size: number;
		/** 配置值 */
		value: number;
	}

	/**
	 * 分页查询 Config 信息
	 *
	 * 成员包括 total, items
	 */
	interface ConfigPageRsp {
		/** 总数 */
		total: number;
		/** Config信息 */
		items: ConfigItem[];
	}

	/**
	 * 批量删除 Config 信息
	 *
	 * 成员包括 ids
	 */
	interface ConfigDeleteReq {
		/** 记录id列表 */
		ids: number[];
	}

	/** Config 无数据返回 */
	interface ConfigNoneRsp { }


	/**
	 * 测试请求
	 *
	 * 成员包括 name
	 */
	interface HelloReq {
		/** 用户名 */
		name: string;
	}

	/**
	 * 测试响应
	 *
	 * 成员包括 greeting
	 */
	interface HelloRsp {
		/** 问候语 */
		greeting: string;
	}

}