

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

 {{#each items}}
 /** {{desc}} */
 declare enum {{name}} {
    {{#each fields}}
    /** {{desc}} */
    {{ name }} = '{{value}}',
    {{/each}}
 }

{{/each}}
    