

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

interface Rsp<T> {
    result: number
    data: T
    message: string
}

declare namespace {{capitalize mod}} {
 {{#each items}}
 {{#if desc}}
    /** {{desc}} */
 {{/if}}
    interface {{name}} {
        {{#each fields}}
        {{#if desc}}
        /** {{desc}} */
        {{/if}}
        {{#if (isArray label)}}
        {{ json }}: {{ convertType type }}[],
        {{else}}
        {{ json }}: {{ convertType type }},
        {{/if}}
        {{/each}}
    }

{{/each}}
}
