
// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import { ajax_get, ajax_post, ajax_any } from "./request";

 {{#each items}}
 {{# if req}}
 /**
  * {{desc}} 
  * @path {{method}} {{url}}
  * @return {{capitalize ../mod}}.{{rsp.name}}
  {{#if codes}}
  * @codes 错误码如下
  {{#each codes}}
  * - {{name}}({{value}}) {{desc}}
  {{/each}}
  {{/if}}
*/
 export const {{name}} = (data: {{capitalize ../mod}}.{{req.name}}): Promise<Rsp<{{capitalize ../mod}}.{{rsp.name}}>> => {
    return ajax_any("{{method}}", "{{url}}", data);
 }
{{/if}}

{{/each}}