package consts

// Generated by niuhe.idl

import "github.com/ma-guo/niuhe"

// 错误类型
var Errors struct {
	*niuhe.IntConstGroup
	NOT_FOUND niuhe.IntConstItem `name:"查找的数据不存在" value:"404"` // value: 404, name: 查找的数据不存在
}

// 语言枚举类
var Language struct {
	*niuhe.StringConstGroup
	ZH niuhe.StringConstItem `name:"中文" value:"zh"` // value: zh, name: 中文
	EN niuhe.StringConstItem `name:"英文" value:"en"` // value: en, name: 英文
}

// 语言类型枚举
var LanguageType struct {
	*niuhe.IntConstGroup
	ZH_CN niuhe.IntConstItem `name:"简体中文" value:"1"` // value: 1, name: 简体中文
	ZH_TW niuhe.IntConstItem `name:"繁体中文" value:"2"` // value: 2, name: 繁体中文
}

func init() {
	niuhe.InitIntConstGroup(&Errors)
	niuhe.InitConstGroup(&Language)
	niuhe.InitIntConstGroup(&LanguageType)
}
